algoritmo "Nome do Programa"

var
num1,num2,num3:real

inicio
escreval("Digite um numero: ")
leia(num1)
escreval("Digite um numero: ")
leia(num2)
escreval("Digite um numero: ")
leia(num3)

se (num1 > num2) e (num1 > num3) entao
    escreval (num1, " é maior entre os 3 números")
senao se (num2 > num1) e (num2 > num3) entao
    escreval (num2, " é maior entre os 3 números")
senao se (num3 > num1) e (num3 > num2) entao
    escreval(num3, " é o maior entre os 3 números")
fimse
fimse
fimse
fimalgoritmo