algoritmo "mês"

var

num:inteiro

inicio

escreval("obs: escreva o digito do mês, exemplo: 1 = janeiro")
escreval("digite um numero que vamos falar o mês e quantos dias tem: ")
leia(num)
se (num = 1) entao
    escreval ("janeiro tem 31 dias")
fimse
se (num = 2) entao
    escreval ("fevereiro tem 28 dias")
fimse
se (num = 3) entao
    escreval ("março tem 31 dias")
fimse
se (num = 4) entao
    escreval ("abril tem 30 dias")
fimse
se (num = 5) entao
    escreval ("maio tem 31 dias")
fimse
se (num = 6) entao
    escreval ("junho tem 30 dias")
fimse
se (num = 7) entao
    escreval ("julho tem 31 dias")
fimse
se (num = 8) entao
    escreval ("agosto tem 31 dias")
fimse
se (num = 9) entao
    escreval ("setembro tem 30 dias")
fimse
se (num = 10) entao
    escreval ("outubro tem 31 dias")
fimse
se (num = 11) entao
    escreval ("novembrotem 30 dias")
fimse
se (num = 12) entao
    escreval ("dezembro tem 31 dias")
fimse

fimalgoritmo