algoritmo "numero extenso"

var
    num: inteiro

inicio

    escreval("Digite um numero de 1 a 100 que vamos escrever por extenso")
    leia(num)
    escolha num 
        caso 1 
            escreval("um")    
        caso 2 
            escreval("dois")
        caso 3 
            escreval("três")
        caso 4 
            escreval("quatro")
        caso 5 
            escreval("cinco")
        caso 6 
            escreval("seis")
        caso 7 
            escreval("sete")
        caso 8 
            escreval("oito")
        caso 9 
            escreval("nove")
        caso 10 
            escreval("dez")
        caso 11 
            escreval("onze")
        caso 12 
            escreval("doze")
        caso 13 
            escreval("treze")
        caso 14 
            escreval("quatorze")
        caso 15 
            escreval("quinze")
        caso 16 
            escreval("dezesseis")
        caso 17 
            escreval("dezessete")
        caso 18 
            escreval("dezoito")
        caso 19 
            escreval("dezenove")
        caso 20 
            escreval("vinte")
        caso 21 
            escreval("vinte e um")
        caso 22 
            escreval("vinte e dois")
        caso 23 
            escreval("vinte e três")
        caso 24 
            escreval("vinte e quatro")
        caso 25 
            escreval("vinte e cinco")
        caso 26 
            escreval("vinte e seis")
        caso 27 
            escreval("vinte e sete")
        caso 28 
            escreval("vinte e oito")
        caso 29 
            escreval("vinte e nove")
        caso 30 
            escreval("trinta")
        caso 31 
            escreval("trinta e um")
        caso 32 
            escreval("trinta e dois")
        caso 33 
            escreval("trinta e três")
        caso 34 
            escreval("trinta e quatro")
        caso 35 
            escreval("trinta e cinco")
        caso 36 
            escreval("trinta e seis")
        caso 37 
            escreval("trinta e sete")
        caso 38 
            escreval("trinta e oito")
        caso 39 
            escreval("trinta e nove")
        caso 40 
            escreval("quarenta")
        caso 41 
            escreval("quarenta e um")
        caso 42 
            escreval("quarenta e dois")
        caso 43 
            escreval("quarenta e três")
        caso 44 
            escreval("quarenta e quatro")
        caso 45 
            escreval("quarenta e cinco")
        caso 46 
            escreval("quarenta e seis")
        caso 47 
            escreval("quarenta e sete")
        caso 48 
            escreval("quarenta e oito")
        caso 49 
            escreval("quarenta e nove")
        caso 50 
            escreval("cinquenta")
        caso 51 
            escreval("cinquenta e um")
        caso 52 
            escreval("cinquenta e dois")
        caso 53 
            escreval("cinquenta e três")
        caso 54 
            escreval("cinquenta e quatro")
        caso 55 
            escreval("cinquenta e cinco")
        caso 56 
            escreval("cinquenta e seis")
        caso 57 
            escreval("cinquenta e sete")
        caso 58 
            escreval("cinquenta e oito")
        caso 59 
            escreval("cinquenta e nove")
        caso 60 
            escreval("sessenta")
        caso 61 
            escreval("sessenta e um")
        caso 62 
            escreval("sessenta e dois")
        caso 63 
            escreval("sessenta e três")
        caso 64 
            escreval("sessenta e quatro")
        caso 65 
            escreval("sessenta e cinco")
        caso 66 
            escreval("sessenta e seis")
        caso 67 
            escreval("sessenta e sete")
        caso 68 
            escreval("sessenta e oito")
        caso 69 
            escreval("sessenta e nove")
        caso 70 
            escreval("setenta")
        caso 71 
            escreval("setenta e um")
        caso 72 
            escreval("setenta e dois")
        caso 73 
            escreval("setenta e três")
        caso 74 
            escreval("setenta e quatro")
        caso 75 
            escreval("setenta e cinco")
        caso 76 
            escreval("setenta e seis")
        caso 77 
            escreval("setenta e sete")
        caso 78 
            escreval("setenta e oito")
        caso 79 
            escreval("setenta e nove")
        caso 80 
            escreval("oitenta")
        caso 81 
            escreval("oitenta e um")
        caso 82 
            escreval("oitenta e dois")
        caso 83 
            escreval("oitenta e três")
        caso 84 
            escreval("oitenta e quatro")
        caso 85 
            escreval("oitenta e cinco")
        caso 86 
            escreval("oitenta e seis")
        caso 87 
            escreval("oitenta e sete")
        caso 88 
            escreval("oitenta e oito")
        caso 89 
            escreval("oitenta e nove")
        caso 90 
            escreval("noventa")
        caso 91 
            escreval("noventa e um")
        caso 92 
            escreval("noventa e dois")
        caso 93 
            escreval("noventa e três")
        caso 94 
            escreval("noventa e quatro")
        caso 95 
            escreval("noventa e cinco")
        caso 96 
            escreval("noventa e seis")
        caso 97 
            escreval("noventa e sete")
        caso 98 
            escreval("noventa e oito")
        caso 99 
            escreval("noventa e nove")
        caso 100 
            escreval("cem")   
    fimescolha
fimalgoritmo