algoritmo "Média do aluno"
var
num1,num2,num3,num4,num5,mda:real
inicio
escreval("qual foi sua nota na primeira prova?: ")
leia(num1)
escreval("qual foi sua nota na segunda prova?: ")
leia(num2)
escreval("qual foi sua nota na terceira prova?: ")
leia(num3)
escreval("qual foi sua nota na quarta prova?: ")
leia(num4)
escreval("qual foi sua nota na quinta prova?: ")
leia(num5)
mda:=(num1+num2+num3+num4+num5)/5
escreval("sua media foi:", mda)
fimalgoritmo